import { describe, expect, it } from "vitest";
import { createProvisionalFormulaPolicy, type FormulaRequest } from "./evaluate";
import { evaluateWithConfidence } from "./confidence";
function fixture() {
  const policy = createProvisionalFormulaPolicy("material-cost", "1.0.0", { createdAt: "2026-01-01T00:00:00Z", createdBy: "Test", reason: "Synthetic", effectiveDates: { from: "2026-01-01", through: null }, confidence: { scoreMeaning: "evidence_not_probability", aggregation: "weakest_component_cap", bands: { high: 85, medium: 65, low: 40 }, rules: [{ id: "provisional", condition: "provisional_policy", inputKey: null, effect: { kind: "cap", maximumScore: 60 }, reason: "Test policy cap" }] } });
  const request: FormulaRequest = { businessDate: "2026-01-01", scopeId: "test", quantityUnit: "piece", allowProvisional: true, inputs: { reported: { amount: "10", scopeId: "test", unit: "piece", source: "mms", category: "production", status: "confirmed", complete: true, evidenceRefs: ["test"] }, material_per_unit: { amount: "5", scopeId: "test", unit: "INR/piece", source: "financial_master", category: "configuration", status: "confirmed", complete: true, evidenceRefs: ["test"] } } };
  const assessed = { score: 100, evidenceRefs: ["test:quality"], method: "Synthetic assessment" };
  return { policy, request, quality: { source_quality: { ...assessed }, mapping_quality: { ...assessed }, formula_reliability: { ...assessed } } };
}
describe("per-result confidence", () => {
  it("caps provisional policy despite excellent source evidence", () => { const f = fixture(); const result = evaluateWithConfidence(f.policy, f.request, f.quality); expect(result.confidence.score).toBe(60); expect(result.confidence.label).toBe("Low"); });
  it.each([0, 20, 39, 40, 59])("weakest evidence wins at %s", score => { const f = fixture(); f.quality.mapping_quality.score = score; expect(evaluateWithConfidence(f.policy, f.request, f.quality).confidence.score).toBe(score); });
  it("does not invent scores or thresholds when evidence is absent", () => { const f = fixture(); expect(evaluateWithConfidence(f.policy, f.request, {}).confidence.score).toBeNull(); delete f.policy.confidence.bands; expect(evaluateWithConfidence(f.policy, f.request, f.quality).confidence.score).toBeNull(); });
  it("does not mask missing material cost with a high score", () => { const f = fixture(); f.request.inputs.material_per_unit = null; const r = evaluateWithConfidence(f.policy, f.request, f.quality); expect(r.calculation.status).toBe("unavailable"); expect(r.confidence.score).toBeNull(); });
  it("requires explicit rules for estimated inputs", () => { const f = fixture(); f.request.inputs.material_per_unit!.status = "estimated"; expect(evaluateWithConfidence(f.policy, f.request, f.quality).confidence.score).toBeNull(); f.policy.confidence.rules.push({ id: "estimated", inputKey: "material_per_unit", condition: "estimated_input", effect: { kind: "cap", maximumScore: 30 }, reason: "Synthetic estimate cap" }); expect(evaluateWithConfidence(f.policy, f.request, f.quality).confidence.score).toBe(30); });
  it("honours evidence-backed hard quality rules", () => { const f = fixture(); f.policy.confidence.rules.push({ id: "source", inputKey: null, condition: "source_quality", effect: { kind: "unavailable" }, reason: "Source must be clean" }); expect(evaluateWithConfidence(f.policy, f.request, f.quality).calculation.status).toBe("available"); f.quality.source_quality.score = 99; expect(evaluateWithConfidence(f.policy, f.request, f.quality).calculation.status).toBe("unavailable"); });
});
